<!DOCTYPE html>
<html>
<head>
    <title>Главная страница</title>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="../css/bootstrap.css">
    <link rel="stylesheet/less" type="text/css" href="../css/style.less">
    <script src="../js/less.js" type="text/javascript"></script>
</head>
<body class="index">
    <?php drawNavBar() ?>
    <div class="span9">

        <h3>Последние сообщения от зарегистрированный пользователей</h3>
        
        <?php
        while ( $row = $sth->fetch() ) { ?>
            <p class="p-registr-messages"><?php echo $row['login'] ?></p>
            <span class="registr-messages"><?php echo $row['message'] ?></span>
            
        <?php } ?>

    </div>
</body>
</html>