<?php
//session_start();
//require '../nav-menu.php'; Так как шаблоны уже в другой папке и делать пхп файл для этой страницы я не буду(да и писать туда нечего) я вместо меню перенаправляю на главную через 2.5с
require '../../hide/config.php'; 
?>

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Успех!</title>
    <link rel="stylesheet" type="text/css" href="../css/bootstrap.css">
    <link rel="stylesheet/less" type="text/css" href="../css/style.less">
    <script src="../js/less.js" type="text/javascript"></script>
    <script>

        function redirect() {
            location="../index.php";
        }
        setTimeout( 'redirect()', 2500);

    </script>
</head>
<body>
    <h3>Спасибо! Ваша жалоба отправлена. Мы внимательно ее изучим, и в случае необходимости, свяжемся с вами.</h3>
    Хотите вернуться на <a href="../index.php">главную страницу?</a>
</body>
</html>
